### ISSUE TITLE
Network Trace - Icon missing when selecting widget in builder mode

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#72]

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Are you referring to the image in the following screenshot?

![image](https://cloud.githubusercontent.com/assets/2959186/6553147/ad530070-c673-11e4-8f0d-5a32fe845feb.png)

**Comment by MikeMillerGIS** [comment]
The page before this, the page with all the widgets when you are selecting the widget.  I will create a screen shot later

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have changed the widget icons. Below are the screenshots. Please confirm.

Widget Selection Screen
![image](https://cloud.githubusercontent.com/assets/2959186/6570634/eb51c31a-c723-11e4-9625-90869ac4ed9d.png)

Widget Config Panel
![image](https://cloud.githubusercontent.com/assets/2959186/6570638/fa62a0d6-c723-11e4-8d9c-a6adc3b6b40a.png)

**Comment by MikeMillerGIS** [comment]
Yes, the image in the first page.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have implemented this in V0.3

**Comment by MikeMillerGIS** [comment]
This issue still exist, there is a name conflict issue.  The widget folder name is NetworkTrace, but the URL is looking for IsolationTrace
![image](https://cloud.githubusercontent.com/assets/2707285/6739958/e1772da4-ce52-11e4-892b-f4cbbefe495e.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS This seems to be related to #71, which will be delivered in the next release

**Comment by MikeMillerGIS** [comment]
resolved
