### ISSUE TITLE
Coordinate Conversion only partially supports +/- as suffix for notation in DD, DDM, DMS

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#800]
from @elinz:

ISSUE: Widget partially supports +/- as suffix in DD, DDM, DMS. For example...
Widget will create correct output for: 45.0+ 100.0- and 45.0+ 100.0+, but will create incorrect output for 45.0- 100.0- and 45.0- 100.0+. Either we fix this for this release or remove +/- suffix support.

**Comment by adgiles** [comment]
Dan,

The Geometry Service on ArcGIS Server provides incorrect results when using +/- as a suffix:

![untitled1](https://cloud.githubusercontent.com/assets/3740334/22064351/1846a826-dd7b-11e6-8d42-3f13f3ce9127.png)

@nfeuerstein Do we want to perform error checking and correction on the input string within the widget before it gets fired to the server or document the valid inputs.

The same goes for long / lat entries #741, #742, #743, #744, #745 

![untitled1](https://cloud.githubusercontent.com/assets/3740334/22064579/1a61718a-dd7c-11e6-8f39-6c5ee48b2a61.png)

**Comment by kgonzago** [comment]
@adgiles Doc'ing valid inputs may be the easiest approach but what is the level of effort to add logic for error checking and correction?

**Comment by elinz** [comment]
@nfeuerstein @adgiles @kgonzago After the release, I'll take this Geometry service issue up with the core team.

**Comment by Dbarnes1** [comment]
Because this is a limitation in core, we are not adding any additional documentation for this release, as we believe it is covered by the coordinate support topic. @elinz I'm assigning this to you to take the issue up with core after this release.

**Comment by elinz** [comment]
@dfoll @Dbarnes1 Verified that in latest .pdf (build 18 jan 2017 12:25) that +|- is not shown as a suffix for DD, DDM and DMS.

**Comment by adgiles** [comment]
fixed please verify

**Comment by elinz** [comment]
@adgiles @kgonzago Still not working correctly.

For DMS the following are not working; they are placed in the wrong hemisphere
1. 45 0 0.0- 100 0 0.0-
2. 45 0 0.0- 100 0 0.0+
3. 100  0 0.0- 45  0 0.0-
4. 100  0 0.0+ 45  0 0.0-

Reassigning back to @adgiles

**Comment by adgiles** [comment]
God Damn regexp, I was accepting the minus sign as a valid second symbol, so it was picking it up as the suffix, should all be good now.

@elinz Please can you test again

**Comment by elinz** [comment]
@adgiles Verified fixed. Closing issue.
